sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.0
  - ruby-head
  - jruby-1.7.20
  - jruby-9.0.5.0
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-1.7.20
  - rvm: jruby-9.0.5.0
